---
- name: In Progress - NTP Configuration Checks
  hosts: cisco
  gather_facts: no
  vars:
    required_servers: []

  tasks:
    - name: Create list of required NTP servers
      set_fact:
        required_servers: "{{ required_servers }} + [ 'ntp server {{ item }}' ]"
      with_items: "{{ std.na.ntp_servers }}"
    
    - name: Parse NTP servers with PyATS
      ansible.utils.cli_parse:
        commmand: "show ntp config"
        parser:
          name: ansilbe.netcommon.pyats
      register: ntp_config
    
    - name: Look at the ntp_config variable
      debug:
        var: ntp_config
...
