---
- name: Parse a device configuration file
  hosts: Cisco_IOSv
  gather_facts: no

  tasks:
    - name: parse show interface
      ansible.utils.cli_parse:
        text: "./files/intf_ex1.txt"
        parser:
          name: ansible.utils.textfsm
          os: nxos
          template_path: "./templates/nxos_show_interface.textfsm"
    
    - name:
      debug:
        var: parse_result
...
