---
- name: Parse Running Configuration
  hosts: Cisco_CSR1Kv, Cisco_IOSv
  gather_facts: no

  tasks:
    - name: Parse AAA commands
      ansible.utils.cli_parse:
        text: "{{ lookup('file', './files/{{ ansible_host }}_run.cfg') }}"
        parser:
          name: ansible.utils.textfsm
          template_path: "./templates/iosxe_aaa_commands.textfsm"
        set_fact: aaa_cmds
    
    - name:
      debug:
        var: aaa_cmds

    - name: Verify AAA Configuration
      assert:
        that:
          - aaa_cmds.0.LOGIN_GROUP == "login default group CP1 local-case"
          - aaa_cmds.0.ENABLE_GROUP == "enable default group CP1 enable"
        fail_msg: "AAA configuration is out of compliance"
        success_msg: "AAA configuration is compliant"
...
