---
- name: Parse Running Configuration
  hosts: Cisco_CSR1Kv
  gather_facts: no

  tasks:
    - name: Parse AAA commands
      ansible.utils.cli_parse:
        text: "{{ lookup('file', './files/test_cfg.txt') }}"
        parser:
          name: ansible.utils.textfsm
          template_path: "./templates/iosxe_aaa_commands.textfsm"
        set_fact: aaa_cmds
    
    - name:
      debug:
        var: aaa_cmds
...
